name: Fly Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  deploy:
    name: Deploy
    needs: elixir-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@1.4
      - run: flyctl deploy --remote-only --no-cache
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
